UF-CSU/club-portal-backend

- app/clubs/services.py
add the functions to count the points and create an event and a recurring event, I hope it helps, I did not understand the part of implementing the link
> adding new functions to services.py

- app/clubs/static/clubs/available-clubs.css
- app/clubs/static/clubs/available-clubs.js
This pull request adds the CSS and JS for the "Available Clubs" page as per issue #24. According to my friend, this CSS and JS make the Available Clubs page more attractive and interactive.
Let me know if there’s anything further you’d like me to adjust. Looking forward to your feedback!
> Available Clubs Page #24

- app/clubs/templates/clubs/available-clubs.html
I sincerely apologize for this mistake, I have edited the JS src to match the name my friend gave it.
> correct  src of JS script

- app/users/views.py
When user is logged in, it now redirects user to the landing page instead of the register page.
> Fixed Register Redirect Issue

- README.md
- pull_request_template.md
Created pull request template for contributors to adhere to when submitting pull requests
Fixes Issue #71
Documentation update
> Created pull_request_template.md and updated the README with Django installation

- app/clubs/static/clubs/club-home.css
- app/clubs/templates/clubs/club-home.html
Completed home club page issue
> mock template of club home page done

- app/app/urls.py
- app/events/apis.py
- app/events/models.py
- app/events/serializers.py
- app/events/viewsets.py
Worked on creating the Events API. I created a serializer and viewset for Events, and implemented filtering by primary club, club ID, and tag.
I'm not the most experienced with Django, so I expect that I'll need to make changes after a review.
Contributes towards #109 (CSU-154).
---
Please delete options that are not relevant.
> Create Events API

- docs/Authentication.md
> finish oauth docs, add auth examples to docs

- app/users/apis.py
- app/users/serializers.py
- app/users/viewsets.py
> add get user api

- app/clubs/serializers.py
I modified the club serializer to return the fields found in the Club model. However, from what I understand, some of the fields (tags and teams) require new nested serializers to be created. Do you want me to create them?
Contributes to #155. (CSU-177)
---
> Add fields to Clubs API

- app/events/views.py
- app/events/viewsets.py
Fixing issues with my last PR regarding event cancellation 
Fixes # (issue)
CSU - 156 
Please delete options that are not relevant.
> small fixes

- Dockerfile
- app/analytics/apis.py
- app/analytics/serializers.py
- app/analytics/viewsets.py
Finished QR Code  api routes and cleaned up deugged messages. Reverted changes I made to get dev mode working.
> Finished QR Code api functionality

- app/polls/serializers.py
- app/polls/tests/test_poll_views.py
Allow polls api to update poll fields
---
> Update poll serializer

- sample.env
Fixed the .sample.env to not break when directly copying for network mode
> Modified sample.env

- app/app/settings.py
- app/clubs/models.py
- app/clubs/serializers.py
- app/clubs/tests/test_club_admin_perms.py
- app/clubs/viewsets.py
- app/core/abstracts/admin.py
- app/core/abstracts/viewsets.py
- app/core/backend.py
- app/events/viewsets.py
- app/utils/permissions.py
- deploy/proxy/default.conf.tpl
- docker-compose.network.yml
- Change network mode to use dev volumes
- Add gzip to nginx
- Optimize queries for events, clubs, and team members
- Add caching to model viewset base for retrieve and list views
---
> Optimize major queries, cache api responses

- .github/workflows/push-docker.yml
- app/app/settings.py
- app/clubs/admin.py
- app/clubs/models.py
- app/clubs/serializers.py
- app/clubs/tests/test_club_admin_perms.py
- app/clubs/viewsets.py
- app/core/abstracts/admin.py
- app/core/abstracts/viewsets.py
- app/core/backend.py
- app/events/tests/test_event_api.py
- app/events/viewsets.py
- app/utils/permissions.py
- deploy/proxy/default.conf.tpl
- docker-compose.network.yml
- Optimize db queries for events, clubs, teams
- Add caching for api GET requests
> Implement caching, optimize queries

- app/clubs/serializers.py
> fix serializer

- app/clubs/admin.py
- app/clubs/defaults.py
- app/clubs/tests/test_club_admin_perms.py
- app/clubs/tests/test_club_apikeys.py
- app/events/models.py
- app/events/services.py
- app/events/tests/test_event_service.py
- app/events/viewsets.py
- app/polls/viewsets.py
- app/querycsv/serializers.py
- app/querycsv/tests/test_upload_data.py
- app/users/models.py
- app/utils/models.py
- app/utils/permissions.py
* fix issue with uploading users changing api keys
* fix minor perm issues
> Feature/improve tests (#286)

- app/clubs/viewsets.py
- app/events/viewsets.py
EventViewset was checking for the add_recurringevent permission, even though it only handles regular events, not recurring events.
---
Please delete options that are not relevant.
> Fix permissions for EventViewset

- app/clubs/models.py
- app/clubs/viewsets.py
- app/events/viewsets.py
Optimize DB queries for the endpoints used by the CSU frontpage through liberal use of `prefetch-` and `select-related`.
---
> Optimize DB queries for CSU frontpage

- app/polls/viewsets.py
Added `prefetch-` and `select-related` to the `PollPreviewViewset`. 
Locally, I saw a ~4x speedup. 
---
Please delete options that are not relevant.
> Prefetch/Select data for PollPreviews
